export type Character = {
  id: string;
  name: string;
  quote: string;
  tags: string[];
  creator: string;
  chats: string; // 대화 수 표기용
  likes: string;
  badge?: "only" | "rising" | "new";
  multiImage?: boolean;
  // 썸네일용 그라디언트 (실제 이미지 대신 아트 카드로 렌더)
  art: { from: string; via: string; to: string; glow: string; emoji: string };
  intro: string;
  firstMessage: string;
};

export const characters: Character[] = [
  {
    id: "kang-dohyun",
    name: "강도현",
    quote: "“어딜 도망가. 아직 대답 못 들었는데.”",
    tags: ["#집착", "#재벌", "#계약연애"],
    creator: "@달빛서고",
    chats: "128.4만",
    likes: "9.2만",
    badge: "only",
    multiImage: true,
    art: { from: "#1a1030", via: "#3b1d5e", to: "#8b2fb8", glow: "#c77dff", emoji: "🖤" },
    intro: "재벌 3세, 하지만 네 앞에서만 무너지는 남자. 계약으로 시작된 관계가 어디까지 갈까.",
    firstMessage: "계약서에 사인한 거, 후회해도 늦었어. …근데 왜 손이 떨려?",
  },
  {
    id: "kyle-arden",
    name: "카일 아르덴",
    quote: "“북부의 겨울은 길다. 그대가 머문다면 견딜 만하겠지.”",
    tags: ["#로판", "#북부대공", "#상처남"],
    creator: "@은빛펜촉",
    chats: "96.1만",
    likes: "7.8만",
    badge: "only",
    multiImage: true,
    art: { from: "#0b1a2e", via: "#173a5e", to: "#3d7ab8", glow: "#7dc4ff", emoji: "❄️" },
    intro: "전장에서 돌아온 냉혈한 대공. 정략결혼으로 만난 그가 조금씩 녹기 시작한다.",
    firstMessage: "그대가 새 대공비인가. …생각보다 겁이 없군.",
  },
  {
    id: "yoo-harin",
    name: "유하린",
    quote: "“오빠, 무대 끝나면 나만 봐야 해. 약속.”",
    tags: ["#아이돌", "#순애", "#비밀연애"],
    creator: "@스테이지라잇",
    chats: "84.7만",
    likes: "6.5만",
    badge: "rising",
    art: { from: "#2e0b26", via: "#5e1747", to: "#b83d8a", glow: "#ff7dc4", emoji: "🎤" },
    intro: "국민 걸그룹 메인보컬. 팬과 연인 사이, 그 아슬아슬한 경계선.",
    firstMessage: "대기실에 왜 들어왔어! …아무한테도 말하면 안 돼. 알았지?",
  },
  {
    id: "baek-moohyuk",
    name: "백무혁",
    quote: "“내 구역에서 다치는 건 나 하나로 충분해.”",
    tags: ["#조직물", "#상처남", "#보호본능"],
    creator: "@흑백필름",
    chats: "72.3만",
    likes: "5.9만",
    multiImage: true,
    art: { from: "#1a1a1a", via: "#2e2318", to: "#8a5a2e", glow: "#ffb35c", emoji: "🥃" },
    intro: "뒷골목을 지배하는 남자. 하지만 너에게만은 세상에서 제일 서툴다.",
    firstMessage: "…여긴 네가 올 곳이 아니야. 다치기 전에 돌아가. 데려다줄 테니까.",
  },
  {
    id: "sien",
    name: "시엔",
    quote: "“인간의 수명은 짧지. 그래서 네 하루가 더 귀하다.”",
    tags: ["#인외", "#용족", "#천년의사랑"],
    creator: "@묘연",
    chats: "68.9만",
    likes: "5.4만",
    badge: "only",
    art: { from: "#0b2e1a", via: "#175e3a", to: "#3db87a", glow: "#7dffc4", emoji: "🐉" },
    intro: "천 년을 산 용족의 마지막 후예. 인간인 너를 만나 처음으로 시간이 아까워졌다.",
    firstMessage: "또 왔군, 작은 인간. …오늘은 무슨 이야기를 들려줄 거지?",
  },
  {
    id: "jung-taeoh",
    name: "정태오",
    quote: "“퇴근 후에 보자는 말, 업무 지시 아닌 거 알지?”",
    tags: ["#오피스", "#연상", "#사내연애"],
    creator: "@야근금지",
    chats: "61.2만",
    likes: "4.8만",
    art: { from: "#101828", via: "#1e3a5f", to: "#2e6da4", glow: "#5cb3ff", emoji: "💼" },
    intro: "완벽주의 팀장. 회의실에선 냉정하지만 단둘이 남으면 눈빛이 달라진다.",
    firstMessage: "보고서는 잘 봤어. 근데… 오늘 저녁에 시간 있어?",
  },
  {
    id: "han-jiwoon",
    name: "한지운",
    quote: "“20년을 옆에 있었는데, 아직도 모르겠어?”",
    tags: ["#소꿉친구", "#순애", "#짝사랑"],
    creator: "@옆집창문",
    chats: "57.8만",
    likes: "4.6만",
    badge: "rising",
    multiImage: true,
    art: { from: "#2e1a0b", via: "#5e4017", to: "#b8873d", glow: "#ffd97d", emoji: "🌻" },
    intro: "옆집에 살던 그 애가 어느새 이렇게 컸다. 우정과 사랑 사이, 답은 정해져 있을지도.",
    firstMessage: "야, 라면 먹고 갈래? …아니 그런 뜻 아니고. 아니 맞나.",
  },
  {
    id: "noah",
    name: "노아",
    quote: "“피보다 달콤한 걸 처음 알았어. 네 목소리.”",
    tags: ["#뱀파이어", "#고수위", "#금단"],
    creator: "@심야도서관",
    chats: "53.1만",
    likes: "4.2만",
    badge: "only",
    art: { from: "#1a0b0b", via: "#3e1017", to: "#8a1e3d", glow: "#ff5c7d", emoji: "🌙" },
    intro: "300살 뱀파이어, 낮에는 앤티크 서점 주인. 너에게서 나는 향이 그를 미치게 한다.",
    firstMessage: "이 시간에 서점에 오는 손님은 오랜만이야. …가까이 와 볼래?",
  },
  {
    id: "seo-eunwoo",
    name: "서은우",
    quote: "“누나, 나 어리다고 무시하면 후회할 텐데.”",
    tags: ["#연하", "#대학생", "#직진남"],
    creator: "@캠퍼스로그",
    chats: "49.5만",
    likes: "3.9만",
    art: { from: "#0b1a2e", via: "#2e175e", to: "#6a3db8", glow: "#b47dff", emoji: "🏀" },
    intro: "과 후배인데 어쩐지 자꾸 마주친다. 우연일까, 계획일까.",
    firstMessage: "누나! 여기서 또 만나네요. …사실 우연 아니에요.",
  },
  {
    id: "mukhyang",
    name: "묵향",
    quote: "“검은 거짓말을 하지 않소. 내 마음도 그렇소.”",
    tags: ["#무협", "#무림맹주", "#첫사랑"],
    creator: "@강호일필",
    chats: "44.2만",
    likes: "3.5만",
    art: { from: "#141414", via: "#2e2e3e", to: "#5e5e8a", glow: "#b3b3ff", emoji: "⚔️" },
    intro: "천하제일검이라 불리는 무림맹주. 강호를 평정했지만 네 앞에선 초식이 꼬인다.",
    firstMessage: "소저, 야심한 시각에 어인 일이오. …호위해 주겠소.",
  },
  {
    id: "lian",
    name: "리안 벨크로프트",
    quote: "“아가씨의 명이라면, 지옥까지도.”",
    tags: ["#집사", "#로판", "#헌신남"],
    creator: "@장미정원",
    chats: "41.7만",
    likes: "3.3만",
    multiImage: true,
    art: { from: "#0b0b1a", via: "#17173e", to: "#3d3d8a", glow: "#7d7dff", emoji: "🕯️" },
    intro: "완벽한 집사, 하지만 그 미소 뒤에 숨긴 것이 있다. 10년째 지켜온 비밀.",
    firstMessage: "기침하셨습니까, 아가씨. 오늘의 홍차는 얼그레이로 준비했습니다.",
  },
  {
    id: "cha-ludwig",
    name: "차루드",
    quote: "“악역이 왜 악역인지, 직접 보여줄까?”",
    tags: ["#빙의물", "#악역", "#혐관"],
    creator: "@책속의남자",
    chats: "38.9만",
    likes: "3.1만",
    badge: "new",
    art: { from: "#1a0b1a", via: "#3e173e", to: "#8a3d6a", glow: "#ff7db3", emoji: "🗡️" },
    intro: "소설 속 최종 악역에게 빙의한 네가 마주친 원작 주인공. 스토리가 뒤틀리기 시작한다.",
    firstMessage: "…이상하군. 원작의 너는 나한테 말을 걸지 않았는데.",
  },
];

export const tagFilters = [
  "전체", "#로판", "#집착", "#순애", "#인외", "#조직물",
  "#오피스", "#아이돌", "#무협", "#뱀파이어", "#혐관", "#연하",
];
